### ISSUE TITLE
should change that

### ISSUE THREAD

**Issue by burningTyger** [CoatingToolbox/coating-toolbox#5]
Hi, I was researching a working polymer app and yours seems to be a treasure trove. Thanks a lot.
But you should remove your personal log in information from the repo.

**Comment by jhans3br** [comment]
Thanks for the heads up. Are you referencing the firebase login?

**Comment by burningTyger** [comment]
Could be, the ones in https://github.com/CoatingToolbox/coating-toolbox/blob/master/src/coating-app-shell.html
